name: github-contribution-grid-snake

on:
  schedule:
    - cron: "0 */12 * * *"
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Generate snake.svg
        uses: Platane/snk@v2
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: dist/snake.svg

      - name: push animation.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: assets
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}